package it.salvatoremichelelombardo.obd2reader;

import android.app.*;import android.os.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private final ExecutorService io=Executors.newSingleThreadExecutor();private final List<BluetoothDevice>devices=new ArrayList<>();private final LinkedHashMap<String,PidReading>readings=new LinkedHashMap<>();private final List<String>dtcs=new ArrayList<>();private Spinner spinner;private TextView output;private Elm327Session session;private String vin="",freeze="";
 @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();ensurePermission();loadBonded();}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24);TextView title=new TextView(this);title.setText("SML OBD2 Reader — read-only");title.setTextSize(22);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title);spinner=new Spinner(this);root.addView(spinner);LinearLayout row=new LinearLayout(this);for(String label:new String[]{"Connetti","Live","DTC","VIN","Freeze","JSON"}){Button b=new Button(this);b.setText(label);row.addView(b,new LinearLayout.LayoutParams(0,-2,1));if(label.equals("Connetti"))b.setOnClickListener(v->connect());else if(label.equals("Live"))b.setOnClickListener(v->live());else if(label.equals("DTC"))b.setOnClickListener(v->readDtcs());else if(label.equals("VIN"))b.setOnClickListener(v->readVin());else if(label.equals("Freeze"))b.setOnClickListener(v->readFreeze());else b.setOnClickListener(v->share());}root.addView(row);output=new TextView(this);output.setText("Seleziona un ELM327 associato. L'app non invia comandi che modificano la ECU.");output.setTextIsSelectable(true);root.addView(output,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void ensurePermission(){for(String p:BluetoothPermissionManager.requiredRuntimePermissions(Build.VERSION.SDK_INT))if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{p},8);}
 private void loadBonded(){try{BluetoothManager m=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);BluetoothAdapter a=m==null?null:m.getAdapter();if(a==null){output.setText("Bluetooth non disponibile");return;}devices.clear();devices.addAll(a.getBondedDevices());List<String>names=new ArrayList<>();for(BluetoothDevice d:devices)names.add((d.getName()==null?"ELM327 / dispositivo":d.getName())+" — "+d.getAddress());spinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));}catch(SecurityException e){output.setText("Concedi il permesso Dispositivi nelle vicinanze e riapri la lista.");}}
 private void connect(){if(devices.isEmpty()){loadBonded();return;}BluetoothDevice d=devices.get(spinner.getSelectedItemPosition());runIo(()->{if(session!=null)session.close();session=new Elm327Session(new BluetoothElm327Transport(d));session.connect();return "Connesso in modalità read-only a "+d.getName();});}
 private void live(){runIo(()->{requireSession();String[]cmds={"0104","0105","010B","010C","010D","010F","0110","0111","012F","0142"};for(String c:cmds){try{String r=session.send(c);if(!r.contains("NO DATA"))readings.put(c,PidDecoder.decode(c,r));}catch(Exception ignored){}}return render();});}
 private void readDtcs(){runIo(()->{requireSession();dtcs.clear();for(String c:new String[]{"03","07","0A"}){String r=session.send(c);for(String d:DtcDecoder.decodeResponse(r))dtcs.add(c+":"+d);}return render();});}
 private void readVin(){runIo(()->{requireSession();vin=VinDecoder.decodeMode09(session.send("0902"));return render();});}
 private void readFreeze(){runIo(()->{requireSession();freeze=session.send("020C00");return render();});}
 private void share(){String json=DiagnosticReportJson.serialize(vin,readings,dtcs,freeze);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/json");i.putExtra(Intent.EXTRA_TEXT,json);startActivity(Intent.createChooser(i,"Condividi report OBD2"));}
 private void requireSession(){if(session==null||!session.isConnected())throw new IllegalStateException("Connetti prima l'adattatore ELM327");}
 private String render(){StringBuilder s=new StringBuilder("VIN: ").append(vin.isEmpty()?"n/d":vin).append("\n\n");for(PidReading r:readings.values())s.append(r).append('\n');s.append("\nDTC: ").append(dtcs.isEmpty()?"nessuno/ND":dtcs).append("\nFreeze frame raw: ").append(freeze.isEmpty()?"n/d":freeze);return s.toString();}
 private interface Work{String run()throws Exception;}private void runIo(Work w){io.execute(()->{try{String r=w.run();runOnUiThread(()->output.setText(r));}catch(Exception e){runOnUiThread(()->output.setText("Errore: "+e.getMessage()));}});}
 @Override protected void onDestroy(){if(session!=null)session.close();io.shutdownNow();super.onDestroy();}
}
